### ISSUE TITLE
v2.2-RC3 sample drops

### ISSUE THREAD

**Issue by darkjacky** [wiedehopf/airspy-conf#3]
It seems v2.2-RC2 and v2.2-RC3 drops a lot of samples compared to v2.2-RC1. With the same config.

v2.2-RC1: CPU 98.7 %, target 95.0 %, adjusting preamble filter: 28 -> 27
v2.2-RC2: Dropped samples, adjusting preamble filter: 27 -> 26
v2.2-RC3: Dropped samples, adjusting preamble filter: 24 -> 23

It is either less stable or there is something using a lot more CPU or something else entirely.

**Comment by wiedehopf** [comment]
Different scaling of -e, use lower -e.
don't use -C 95, use -C 85 .... then you don't drop samples, simple.
