### ISSUE TITLE
On VRS, Altitude often shows incorrect GND value

### ISSUE THREAD

**Issue by Hermite123456** [wiedehopf/airspy-conf#4]
Since RC22, I am noticing many incorrect altitude values, namely GND, when planes are actualy way out in the air.
It alternates from GND to the correct values within 5 seconds, and does it multiple times.

Am running on PI4 with an Airspy Mini.

pi@raspberrypi:~ $ sudo systemctl status  airspy_adsb
● airspy_adsb.service - Airspy ADS-B receiver
   Loaded: loaded (/lib/systemd/system/airspy_adsb.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-10-29 17:43:01 EDT; 6min ago
     Docs: https://discussions.flightaware.com/t/howto-airspy-mini-piaware-dump1090-fa-configuration/44343
 Main PID: 16560 (airspy_adsb)
    Tasks: 9 (limit: 4915)
   CGroup: /system.slice/airspy_adsb.service
           └─16560 /usr/local/bin/airspy_adsb -v -t 60 -f 1 -w 6 -e 16 -E 30 -C 80 -b -l 47787:beast -c 127.0.0.1:30004:beast -g 19 -m 12 -S /run/airspy_adsb/stats.json

Oct 29 17:43:01 raspberrypi systemd[1]: Started Airspy ADS-B receiver.
Oct 29 17:43:01 raspberrypi airspy_adsb[16560]: airspy_adsb v2.2-RC30
Oct 29 17:43:01 raspberrypi airspy_adsb[16560]: Listening for beast clients on port 47787
Oct 29 17:43:01 raspberrypi airspy_adsb[16560]: Acquired Airspy device with serial 685C68DC336A4A43
Oct 29 17:43:01 raspberrypi airspy_adsb[16560]: Decoding started at 12 MSPS (Gain: 19; CPU target: 80 %)
Oct 29 17:43:02 raspberrypi airspy_adsb[16560]: Push client connected to 127.0.0.1:30004 (beast)

Anybody else observing this behaviour?

Tks.

![image](https://user-images.githubusercontent.com/54645050/139506164-bb7d16d1-805a-4c78-94e6-e9f1bc897ad2.png)

**Comment by wiedehopf** [comment]
It's VRS being stupid not dealing well with spurious messages.

adding -P 10 or -P 5 is the recommended solution if you have to use programs that can't handle occasional bad messages ...
The lower -P, the less of those problematic non-CRC messages you'll get.

**Comment by Hermite123456** [comment]
Perfect, P -5 did the trick!, Tks.
