### ISSUE TITLE
Unexpected message during install

### ISSUE THREAD

**Issue by JRG1956** [wiedehopf/airspy-conf#5]
Encountered a very minor issue when installing airspy_adsb on a fresh install of Bookworm - got the following message, though the install worked as expected.

----------------
Seems your system is a bit old, performance may be worse than on buster or newer!
 < libc-2.28.so
----------------

**Comment by wiedehopf** [comment]
Please run the update, this issue should be fixed:

https://github.com/wiedehopf/airspy-conf/tree/master?tab=readme-ov-file#update

**Comment by JRG1956** [comment]
Thanks - that ran successfully with the following message:

2.36 >= 2.28

(Apologies for the bolded text in my message above - didn't realise that the dashed lines above and below the message text invoked formatting)

**Comment by wiedehopf** [comment]
Most places accept this formatting:
\`\`\`
code or log
\`\`\`

**Comment by wiedehopf** [comment]
No worries about the formatting though as long as it's readable :)

You running arm64?

**Comment by JRG1956** [comment]
Yes - 64 bit Bookworm on a Pi 5B

I have just acquired an Airspy R2 and plan on experimenting with 24 Maps and -e 60 to see if the Pi 5 can handle the load and also run a second RTLSDR dongle for ais-catcher.

**Comment by wiedehopf** [comment]
The load is a non-issue on pi4 so i would expect the same on a pi5.

The only issue would be USB bandwidth but the pi5 might have 2 separate USB chips so .. if that's the case where you plug in both devices will matter.

There is very limited upside of running beyond 20 MSPS really, so might just want to go with that and enable bit packing to reduce USB bandwidth a bit.

**Comment by JRG1956** [comment]
Yes - it is the USB bandwidth "load" that I'm interested in. I'm running with 24Msps and -e 60 and the total processor load on the  Pi 5 is only 33%. I'm not expecting the higher sample rate to make much/any difference - just got bored and felt like experimenting.

Re plugging in the devices - Caius mentioned on the Flightaware forum the Pi5 pairs a controller(?) for a USB2 port and a USB3 horizontally, rather than separating USB2 and USB3. I had thought that available USB current on the Pi4 was an issue, that Pi5 can deliver 1600mA rather than 1200mA on the Pi4, but I'm not sure that is really an issue. Will test to find out.

Thanks as always for all your great applications.

**Comment by wiedehopf** [comment]
Make sure that you're not running via the CPU control which respects the -E 20 that is the default in the config. Anyhow the config file should explain that.

**Comment by JRG1956** [comment]
Currently running with these parameters (mainly the same as my airspy mini "production" Pi4:

-v -t 300 -f 1 -w 5 -P 7 -e 60 -R rms -l 47787:beast -c 127.0.0.1:30004:beast -g auto -m 24 -S /run/airspy_adsb/stats.json
